name: CI Build

on: [pull_request]

env:
  LC_ALL: en_US.UTF-8

jobs:
  CheckSourceFormatting:
    name: Check source formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Check source formatting task
        shell: bash
        run: |
          ./gradlew --no-daemon checkSourceFormatting
  LinuxJDK21:
    name: Linux JDK21
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.properties.outputs.version }}
      changelog: ${{ steps.properties.outputs.changelog }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build
        shell: bash
        run: |
          ./gradlew --no-daemon --scan clean test verifyPlugin

  CompatibilityChecking:
    name: Check compatibility
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build
        shell: bash
        run: |
          ./gradlew --no-daemon clean -x test buildPlugin

      - name: Verify compatibility
        id: verify
        uses: ChrisCarini/intellij-platform-plugin-verifier-action@latest

        with:
         ide-versions: |
          ideaIC:2025.1
          ideaIU:2025.1
         mute-plugin-problems: TemplateWordInPluginId